### ISSUE TITLE
get_facts fails on both network_cli and netconf

### ISSUE THREAD

**Issue by LukeDRussell** [ansible-network/juniper_junos#26]
### Task
```yaml

  - name: use ansible-network provider roles to gather facts
    include_role:
      name: "{{ ansible_network_provider }}"
      tasks_from: get_facts.yaml
    vars:
      subset: 
        - system
      ansible_connection: network_cli
```
### Result
```sh

TASK [ansible-network.juniper_junos : run rpc command] ***************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
fatal: [qatfw2bj-sc1]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/4032956/.ansible/tmp/ansible-local-94658eg4njtmh/ansible-tmp-1543890239.3495862-60100278778874/AnsiballZ_junos_command.py", line 113, in <module>
        _ansiballz_main()
      File "/home/4032956/.ansible/tmp/ansible-local-94658eg4njtmh/ansible-tmp-1543890239.3495862-60100278778874/AnsiballZ_junos_command.py", line 105, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/4032956/.ansible/tmp/ansible-local-94658eg4njtmh/ansible-tmp-1543890239.3495862-60100278778874/AnsiballZ_junos_command.py", line 48, in invoke_module
        imp.load_module('__main__', mod, module, MOD_DESC)
      File "/tmp/ansible_junos_command_payload_8YJyWe/__main__.py", line 451, in <module>
      File "/tmp/ansible_junos_command_payload_8YJyWe/__main__.py", line 371, in main
    TypeError: 'NoneType' object is not iterable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

### Task
```yaml
  - name: use ansible-network provider roles to gather facts
    include_role:
      name: "{{ ansible_network_provider }}"
      tasks_from: get_facts.yaml
    vars:
      subset: 
        - system
      ansible_connection: netconf
```
### Result
```sh
TASK [ansible-network.juniper_junos : run command] *******************************************************************************************************************************
fatal: [qatfw2bj-sc1]: FAILED! => changed=false
  msg: jxmlease is required but does not appear to be installed. It can be installed using `pip install jxmlease`
```
```sh
pip list
$ pip list
Package           Version
----------------- ---------
ansible           2.7.2
asn1crypto        0.24.0
astroid           2.0.4
atomicwrites      1.2.1
attrs             18.2.0
bcrypt            3.1.4
certifi           2018.8.24
cffi              1.11.5
chardet           3.0.4
cryptography      2.3.1
idna              2.7
isort             4.3.4
Jinja2            2.10
junos-eznc        2.2.0
jxmlease          1.0.1
lazy-object-proxy 1.3.1
lxml              4.2.3
MarkupSafe        1.0
mccabe            0.6.1
more-itertools    4.3.0
ncclient          0.6.0
netaddr           0.7.19
paramiko          2.4.2
pip               18.1
pluggy            0.8.0
py                1.7.0
pyasn1            0.4.4
pycparser         2.19
pylint            2.1.1
PyNaCl            1.3.0
pyserial          3.4
pytest            4.0.0
PyYAML            3.13
requests          2.19.1
scp               0.11.0
selectors2        2.0.1
setuptools        39.0.1
six               1.11.0
typed-ast         1.1.0
urllib3           1.23
wrapt             1.10.11
```

**Comment by LukeDRussell** [comment]
```sh
ansible 2.7.2
  config file = /home/4032956/Documents/network-automation/ansible.cfg
  configured module search path = ['/home/4032956/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/4032956/.pyenv/versions/3.6.6/envs/network-automation/lib/python3.6/site-packages/ansible
  executable location = /home/4032956/.pyenv/versions/3.6.6/envs/network-automation/bin/ansible
  python version = 3.6.6 (default, Jul 23 2018, 12:40:23) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
ansible-network.juniper_junos version == v2.7.1

**Comment by ganeshrn** [comment]
@LukeRussell It seems there are two different issues one for connection=network_cli and other for connection= netconf

**For network_cli:**
Have you modified `get_facts_command_map.yaml` to give `rpc` as an input? The error log shows `run rpc command` task in `includes/cli/run.yaml` fails, which will be invoked when rpc is given as input in `get_facts_command_map.yaml`.
For network_cli transport, `rpcs` are not supported. I now realize that I need to add check in `includes/cli/run.yaml` to throw an error in case rpc is given as input with cli transport.

**For netconf:**
```
msg: jxmlease is required but does not appear to be installed.
```
This seems more like an environment issue. The junos_command module that ships with ansible package requires `jxmlease` library to convert xml to json. Can you please check if the python executable path that run junos_command.py file has `jxmlease` installed.

**Comment by ganeshrn** [comment]
needs_info

**Comment by networkeng1** [comment]
.
